//
// Created by josue on 8/15/2021.
//

#ifndef TIPOS_DE_DATO_PRIMITIVOS_Y_TIPOS_DE_DATO_ESTRUCTURADOS_MENU_H
#define TIPOS_DE_DATO_PRIMITIVOS_Y_TIPOS_DE_DATO_ESTRUCTURADOS_MENU_H


class menu {
public:
    int options;

};


#endif //TIPOS_DE_DATO_PRIMITIVOS_Y_TIPOS_DE_DATO_ESTRUCTURADOS_MENU_H
